apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: xmlsign
spec:
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer  # Kind will make this accessible via port-forward or ingress