apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: xmlsign
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_PASSWORD: QWRlbG1hc2tvdDI1  # Adelmaskot25
  TUNNEL_TOKEN: ZXlKaElqb2laVEEyWm1GalltRTNZakE0TURaalpXVTRaR0k1T1RreE16WXlaV0V6TjJZaUxDSjBJam9pWXpVMU5UVTJOMlkxTFRobFlUSXRORFJtTUMxaVptRTJMVE01WVdKaE5EVXpaRFEyTkNJc0luTWlPaUpOUkVrMVRWZE5NV1kxVFVkSlZDMU5SR2xtWWkwME5HWjNMV0k1WkVoMFdHUmpaelptWmtJMVRqZE5lQ0o5  # Your tunnel token
